import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
import { createConsolidationPoint,toggleConsolidationPoint } from "./actions";
export const dynamic="force-dynamic";
export default async function Page(){
 await AuthorizationService.requirePermission("WAREHOUSE_VIEW");
 const [warehouses,points,locations]=await Promise.all([
  prisma.warehouse.findMany({where:{isActive:true},orderBy:{code:"asc"},select:{id:true,code:true,name:true}}),
  prisma.consolidationPoint.findMany({include:{warehouse:{select:{code:true,name:true}},location:{select:{code:true,section:true,level:true,bin:true}},_count:{select:{tasks:true}}},orderBy:[{warehouseId:"asc"},{code:"asc"}]}),
  prisma.warehouseLocation.findMany({where:{isActive:true},orderBy:[{warehouseId:"asc"},{sortOrder:"asc"}],take:2000,select:{id:true,warehouseId:true,code:true,section:true,level:true,bin:true}}),
 ]);
 return <section className="p-6 lg:p-10"><div><h1 className="text-4xl font-bold">Konsolidasyon Noktaları</h1><p className="mt-2 text-slate-500">Çoklu Zone siparişlerinin fiziksel birleşme noktalarını yönetin.</p></div>
 <div className="mt-8 grid gap-8 2xl:grid-cols-[420px_1fr]"><form action={createConsolidationPoint} className="h-fit rounded-2xl bg-white p-6 shadow"><h2 className="text-xl font-bold">Yeni Nokta</h2><div className="mt-5 space-y-4"><select name="warehouseId" required className="w-full rounded-xl border p-3"><option value="">Depo seçin</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.code} - {w.name}</option>)}</select><input name="code" required placeholder="CONS-01" className="w-full rounded-xl border p-3 uppercase"/><input name="name" required placeholder="Konsolidasyon Alanı 1" className="w-full rounded-xl border p-3"/><select name="locationId" className="w-full rounded-xl border p-3"><option value="">Fiziksel lokasyon (opsiyonel)</option>{locations.map(l=><option key={l.id} value={l.id}>{warehouses.find(w=>w.id===l.warehouseId)?.code} · {[l.code,l.section,l.level,l.bin].filter(Boolean).join("-")}</option>)}</select><button className="w-full rounded-xl bg-blue-900 p-3 font-bold text-white">Nokta Oluştur</button></div></form>
 <div className="overflow-x-auto rounded-2xl bg-white shadow"><table className="w-full min-w-[800px] text-left"><thead className="bg-blue-900 text-white"><tr><th className="p-4">Nokta</th><th className="p-4">Depo</th><th className="p-4">Lokasyon</th><th className="p-4">Görev</th><th className="p-4">Durum</th><th className="p-4"></th></tr></thead><tbody>{points.map(p=><tr key={p.id} className="border-b"><td className="p-4"><b>{p.code}</b><div>{p.name}</div></td><td className="p-4">{p.warehouse.code}<div className="text-xs text-slate-500">{p.warehouse.name}</div></td><td className="p-4">{p.location?[p.location.code,p.location.section,p.location.level,p.location.bin].filter(Boolean).join("-"):"-"}</td><td className="p-4">{p._count.tasks}</td><td className="p-4">{p.isActive?"Aktif":"Pasif"}</td><td className="p-4"><form action={toggleConsolidationPoint.bind(null,p.id,p.isActive)}><button className="rounded-lg border px-3 py-2 font-bold">{p.isActive?"Pasif Yap":"Aktifleştir"}</button></form></td></tr>)}</tbody></table></div></div></section>;
}