import Link from "next/link";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
import { ManualWaveReportingService,formatIstanbul } from "@/modules/manual-wave/services/manual-wave-reporting.service";
import { WmsContextService } from "@/modules/wms-context/services/wms-context.service";

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) { const q=await searchParams; const user=await AuthorizationService.requirePermission("MANUAL_WAVE_REPORT_VIEW"); const scope=await WmsContextService.requireActiveContext(user.id,user.isAdminUser); const mode=(q.mode||"code") as "code"|"primaryBarcode"|"additionalBarcode"|"thm"; const result=q.value?await ManualWaveReportingService.queryProductOperations(scope,{mode,value:q.value,page:Number(q.page)||1,pageSize:Number(q.pageSize)||50,includeReversed:q.includeReversed==="1"}):null; const query=new URLSearchParams(Object.entries(q).filter((x):x is [string,string]=>Boolean(x[1])));
return <main className="p-6 space-y-5"><Link href="/admin">← Yönetime dön</Link><h1 className="text-2xl font-bold">Manuel Dalga Ürün / THM Sorgu</h1><form className="flex flex-wrap gap-3 border rounded-xl p-4"><select name="mode" defaultValue={mode}><option value="code">Ürün kodu</option><option value="primaryBarcode">Ana barkod</option><option value="additionalBarcode">Ek barkod</option><option value="thm">THM barkodu (ST-...)</option></select><input name="value" required defaultValue={q.value} placeholder="Tam değer" className="border px-3"/><select name="pageSize" defaultValue={q.pageSize||"50"}>{[25,50,100].map(x=><option key={x}>{x}</option>)}</select><label><input type="checkbox" name="includeReversed" value="1" defaultChecked={q.includeReversed==="1"} /> Ters kayıtları göster</label><button className="bg-slate-900 text-white rounded px-4">Sorgula</button>{result ? <a className="bg-emerald-700 text-white rounded px-4 py-2" href={`/admin/manual-wave/product-query/export?${query}`}>Excel</a> : null}</form>
{result?.thmSummary&&<section className="rounded-xl bg-blue-50 p-4"><h2 className="font-bold">THM Özeti</h2><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(result.thmSummary,(_,v)=>typeof v==="bigint"?Number(v):v,2)}</pre></section>}
{result&&<><p>{result.total} kayıt</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["Ürün","Barkod","Dalga","Hedef","THM / Orijinal","Durum","Miktar","Operatör","Tarih","Geri alma"].map(x=><th className="text-left p-2" key={x}>{x}</th>)}</tr></thead><tbody>{result.rows.map((r)=><tr key={String(r.id)} className="border-t"><td className="p-2">{String(r.productCode)} — {String(r.productName)}</td><td>{String(r.barcode)}</td><td>{String(r.waveNo)}</td><td>{String(r.customerCode||r.distributionCode)} — {String(r.customerName)}</td><td>{String(r.thmBarcode)} / {String(r.originalThmBarcode)}</td><td>{String(r.status)}</td><td>{String(r.quantity)}</td><td>{String(r.operator)}</td><td>{formatIstanbul(r.createdAt as Date)}</td><td>{r.reversedAt?`${formatIstanbul(r.reversedAt as Date)} / ${String(r.reversedBy||"")} / ${String(r.reversalReason||"")}`:"-"}</td></tr>)}</tbody></table></div>{!result.rows.length&&<p className="p-4 text-slate-500">Tam eşleşen kayıt bulunamadı.</p>}<nav className="flex gap-3">{result.page>1&&<Link href={`?${new URLSearchParams({...Object.fromEntries(query),page:String(result.page-1)})}`}>← Önceki</Link>}{result.page*result.pageSize<result.total&&<Link href={`?${new URLSearchParams({...Object.fromEntries(query),page:String(result.page+1)})}`}>Sonraki →</Link>}</nav></>}</main> }
