"use client";
import { Fragment, useMemo, useState } from "react";
type D={thm:string;orderNumber:string;productCode:string;productName:string;quantity:number;companyCode:string;companyName:string;city:string;district:string;orderType:string;packer:string};
type R={id:string;warehouseCode:string;date:string;thm:string;quantity:number;status:string;details:D[]};
export default function ShippingBoxDetailTable({rows}:{rows:R[]}){
 const[open,setOpen]=useState<string[]>([]);
 const total=useMemo(()=>rows.reduce((n,r)=>n+r.quantity,0),[rows]);
 return <div className="overflow-x-auto rounded-2xl border bg-white shadow-sm"><div className="border-b bg-slate-50 px-4 py-3 text-sm font-bold">Kayıt: {rows.length} · Toplam Miktar: {total}</div><table className="w-full min-w-[1150px] text-sm"><thead className="bg-slate-100"><tr><th className="p-3">Aç</th><th className="p-3 text-left">Depo Kodu</th><th className="p-3">Tarih</th><th className="p-3 text-left">Koli No</th><th className="p-3 text-right">Miktar</th><th className="p-3">Durum</th></tr></thead><tbody>{rows.map(r=><Fragment key={r.id}><tr className="border-t font-semibold"><td className="p-3 text-center"><button type="button" onClick={()=>setOpen(s=>s.includes(r.id)?s.filter(x=>x!==r.id):[...s,r.id])} className="text-xl font-black">{open.includes(r.id)?"−":"+"}</button></td><td className="p-3">{r.warehouseCode}</td><td className="p-3 text-center">{r.date}</td><td className="p-3 font-black">{r.thm}</td><td className="p-3 text-right">{r.quantity}</td><td className="p-3 text-center">{r.status}</td></tr>{open.includes(r.id)&&<tr className="bg-blue-50/40"><td></td><td colSpan={5} className="p-3"><table className="w-full min-w-[1050px] text-xs"><thead className="bg-white"><tr><th className="p-2">Sevk THM No</th><th className="p-2">Sipariş Numarası</th><th className="p-2">Ürün Kodu</th><th className="p-2">Ürün Tanımı</th><th className="p-2">Miktar</th><th className="p-2">Firma Kodu</th><th className="p-2">Firma Ünvanı</th><th className="p-2">İl</th><th className="p-2">İlçe</th><th className="p-2">Sipariş Tipi</th><th className="p-2">Kolileyen Personel</th></tr></thead><tbody>{r.details.map((d,i)=><tr key={i} className="border-t"><td className="p-2 font-black">{d.thm}</td><td className="p-2">{d.orderNumber}</td><td className="p-2">{d.productCode}</td><td className="p-2">{d.productName}</td><td className="p-2 text-right">{d.quantity}</td><td className="p-2">{d.companyCode}</td><td className="p-2">{d.companyName}</td><td className="p-2">{d.city}</td><td className="p-2">{d.district}</td><td className="p-2">{d.orderType}</td><td className="p-2">{d.packer}</td></tr>)}</tbody></table></td></tr>}</Fragment>)}</tbody></table>{!rows.length&&<p className="p-8 text-center font-bold text-slate-500">Filtreye uygun koli bulunamadı.</p>}</div>
}
