import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
type SearchParams=Promise<{wave?:string;waveNo?:string;tab?:string}>;
export default async function Page({searchParams}:{searchParams:SearchParams}){
 await AuthorizationService.requireRfAccess("PICKING_EXECUTE"); const p=await searchParams;
 const waves=await prisma.wave.findMany({orderBy:{createdAt:"desc"},take:100,select:{id:true,waveNo:true,status:true,distributions:{orderBy:{sequenceNumber:"asc"},select:{id:true,sequenceNumber:true,customerCode:true,customerName:true,plannedQuantity:true,packedQuantity:true,lines:{select:{productId:true,plannedQuantity:true,packedQuantity:true}}}}}});
 const selected=waves.find(w=>w.id===p.wave||w.waveNo===p.waveNo||w.waveNo===p.wave)??waves[0]??null; const ds=selected?.distributions??[];
 const stores=ds.length,orders=ds.reduce((s,d)=>s+d.plannedQuantity,0),distributed=ds.reduce((s,d)=>s+d.packedQuantity,0),remaining=Math.max(0,orders-distributed);
 const sku=new Set<number>(); ds.forEach(d=>d.lines.forEach(l=>{if(l.plannedQuantity>l.packedQuantity)sku.add(l.productId)})); const completion=orders?Math.round(distributed/orders*100):0; const tab=p.tab==="remaining"?"remaining":"stores";
 return <section className="-mx-3 -my-4 min-h-screen bg-slate-100 sm:-mx-4"><header className="bg-slate-950 px-4 py-4 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between"><div><p className="text-[10px] font-black uppercase text-cyan-300">Manual Wave Sorting</p><h1 className="text-xl font-black">Wave Dağılım Özeti</h1><p className="text-xs text-slate-300">Mağaza bazında sipariş, dağıtılan ve kalan dağılım</p></div><Link href="/rf/packing" className="rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold">Dağılıma Dön</Link></div></header>
 <main className="mx-auto max-w-7xl space-y-4 p-4"><form className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-black">Wave Seçimi</h2><p className="text-xs text-slate-500">Listeden bir Wave seçebilir veya Wave numarasını elle girebilirsiniz.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="text-xs">Wave Listesi<select name="wave" defaultValue={selected?.id??""} className="mt-2 w-full rounded-lg border p-3">{waves.map(w=><option key={w.id} value={w.id}>{w.waveNo} - {w.status}</option>)}</select></label><label className="text-xs">Wave No Elle Gir<input name="waveNo" defaultValue={selected?.waveNo??""} className="mt-2 w-full rounded-lg border p-3"/></label><button className="self-end rounded-lg bg-slate-950 px-5 py-3 text-sm font-black text-white">Özeti Getir</button></div></form>
 {selected&&<><div className="flex items-center justify-between"><div><h2 className="text-lg font-black">Wave {selected.waveNo}</h2><p className="text-xs text-slate-500">{stores} mağaza</p></div><span className="rounded-lg bg-slate-950 px-4 py-2 text-xs font-black text-white">Tamamlanma %{completion}</span></div><div className="grid grid-cols-2 gap-3 md:grid-cols-5"><K l="Mağaza" v={stores}/><K l="Sipariş" v={orders}/><K l="Dağıtılan" v={distributed}/><K l="Kalan Dağılım" v={remaining} red/><K l="Kalan SKU" v={sku.size}/></div>
 <nav className="flex gap-2 rounded-xl bg-white p-2"><Link href={`?wave=${selected.id}&tab=stores`} className={`rounded-lg px-4 py-2 text-xs font-black ${tab==="stores"?"bg-slate-950 text-white":""}`}>Mağaza Özeti</Link><Link href={`?wave=${selected.id}&tab=remaining`} className={`rounded-lg px-4 py-2 text-xs font-black ${tab==="remaining"?"bg-slate-950 text-white":""}`}>Genel Kalan Detayı</Link></nav>
 <div className="overflow-x-auto rounded-xl bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-950 text-white"><tr>{(tab==="stores"?["Wave No","Mağaza Kodu","Mağaza İsmi","Sipariş SKU","Sipariş Toplam","Dağıtılan SKU","Dağıtılan Toplam","Kalan SKU","Kalan Toplam"]:["Mağaza Kodu","Mağaza İsmi","Kalan SKU","Kalan Adet"]).map(x=><th key={x} className="px-3 py-3">{x}</th>)}</tr></thead><tbody>{ds.map(d=>{const remain=d.lines.filter(l=>l.plannedQuantity>l.packedQuantity); const vals=tab==="stores"?[selected.waveNo,d.customerCode||String(d.sequenceNumber),d.customerName,new Set(d.lines.map(l=>l.productId)).size,d.plannedQuantity,new Set(d.lines.filter(l=>l.packedQuantity>0).map(l=>l.productId)).size,d.packedQuantity,new Set(remain.map(l=>l.productId)).size,Math.max(0,d.plannedQuantity-d.packedQuantity)]:[d.customerCode||String(d.sequenceNumber),d.customerName,new Set(remain.map(l=>l.productId)).size,Math.max(0,d.plannedQuantity-d.packedQuantity)];return <tr key={d.id} className="border-b">{vals.map((v,i)=><td key={i} className={`px-3 py-3 ${i>=vals.length-2?"font-bold text-red-600":""}`}>{v}</td>)}</tr>})}</tbody></table></div></>}</main></section>
}
function K({l,v,red}:{l:string;v:number;red?:boolean}){return <div className={`rounded-xl border p-4 ${red?"border-red-200 bg-red-50":"bg-white"}`}><p className="text-xs text-slate-500">{l}</p><p className={`mt-2 text-2xl font-black ${red?"text-red-700":""}`}>{v.toLocaleString("tr-TR")}</p></div>}
