import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
import EcommerceReturnReceivingPanel from "@/components/admin/EcommerceReturnReceivingPanel";
import { closeEcommerceReturnWithoutRefund, createRefundApprovalRecord, markEcommerceRefundCompleted, matchEcommercePreReceiptToOrder, resolveEcommerceReturnInspectionRefund } from "./actions";

export const dynamic="force-dynamic";

const statusLabel=(v:string)=>({PRE_RECEIVED:"Ön Kabul",RECEIVING:"İade Giriş Devam Ediyor",QUALITY_CONTROL:"Kalite Kontrol",PARTIALLY_COMPLETED:"Kısmi Tamamlandı",WAREHOUSE_COMPLETED:"Depo İşlemi Tamamlandı",FINANCE_PENDING:"Finans Bekliyor",COMPLETED:"Tamamlandı",REJECTED:"Reddedildi",CANCELLED:"İptal",WAITING:"Bekliyor",ELIGIBLE:"İadeye Uygun",REVIEW_REQUIRED:"İnceleme Bekliyor",REQUESTED:"İade Talebi Oluşturuldu",REFUNDED:"Para İadesi Yapıldı"}[v]??v);

export default async function Page({searchParams}:{searchParams:Promise<{code?:string}>}){
 await AuthorizationService.requireAdminPortalAccess();
 const params=await searchParams;
 const code=String(params.code??"").trim().toUpperCase();
 const pre=code?await prisma.ecommerceReturnPreReceipt.findFirst({
   where:{scannedCode:code},
   include:{
     carrier:true,warehouse:true,
     originalOrder:{include:{customer:true}},
     ecommerceReturn:{include:{items:true,refunds:{orderBy:{createdAt:"desc"}},inspections:{orderBy:{inspectedAt:"desc"},include:{ecommerceReturnItem:{select:{productCode:true,productName:true}}}}}},
   },
 }):null;
 const recent=await prisma.ecommerceReturn.findMany({take:30,orderBy:{createdAt:"desc"},include:{originalOrder:{select:{orderNumber:true,customer:{select:{companyName:true}}}},preReceipts:{take:1,orderBy:{receivedAt:"desc"},include:{carrier:true}},items:true}});

 return <div className="min-w-[1100px] p-6">
  <div className="mb-5 flex items-start justify-between"><div><p className="text-sm font-bold text-slate-500">E-Ticaret Yönetimi / İade</p><h1 className="text-3xl font-black">E-Ticaret İade Giriş</h1><p className="mt-1 text-sm text-slate-500">Ön kabul → eşleştirme → ürün okutma → kalite → stok → finans.</p></div><Link href="/admin/e-ticaret/return-reconciliation" className="rounded-xl border px-4 py-3 font-black">Kargo İade Mutabakatı</Link></div>

  <form className="rounded-2xl border bg-white p-5 shadow-sm"><label className="text-sm font-black">İade Kodu / Kargo Barkodu</label><div className="mt-2 flex gap-2"><input name="code" defaultValue={code} autoFocus className="flex-1 rounded-xl border-2 border-blue-500 px-4 py-3 text-lg font-bold uppercase" placeholder="Ön kabulde okutulan barkodu okutun..."/><button className="rounded-xl bg-blue-700 px-6 font-black text-white">İadeyi Aç</button></div></form>

  {code&&!pre&&<div className="mt-4 rounded-2xl border-2 border-red-300 bg-red-50 p-5 text-red-950"><h2 className="text-lg font-black">⚠ Ön kabul bulunamadı</h2><p className="mt-1 font-semibold">Ön kabul yapılmadan E-Ticaret İade Giriş'e devam edilemez. Şimdi oluşturulacak kayıt mutabakat raporunda Geç Ön Kabul olarak işaretlenecek.</p><Link href="/rf/ecommerce-return-pre-receipt?late=1" className="mt-3 inline-block rounded-xl bg-red-700 px-4 py-3 font-black text-white">Geç Ön Kabul Yap</Link></div>}

  {pre&&<div className="mt-4">
   <div className="mb-4 flex items-center justify-between rounded-2xl border border-emerald-300 bg-emerald-50 p-4"><div><h2 className="font-black text-emerald-950">✓ Ön kabul doğrulandı</h2><p className="text-sm font-semibold">{pre.preReceiptNumber} · {pre.warehouse.code} · {pre.carrier.name} · {pre.mode==="RETURN_CODE"?"İade Kodu":"Kargo Barkodu"}</p></div><div className="text-right text-sm font-bold"><p>{pre.matchStatus}</p><p>{pre.outcome}</p></div></div>

   {(pre.outcome==="RETURN_TO_CARRIER"||pre.outcome==="RETURNED_TO_CARRIER")&&<div className="rounded-2xl border border-amber-300 bg-amber-50 p-5 font-black text-amber-950">Bu gönderi iade girişine kapalıdır; kargoya geri teslim sürecindedir.</div>}

   {!pre.ecommerceReturn&&pre.mode==="CARGO_BARCODE"&&pre.outcome!=="RETURN_TO_CARRIER"&&pre.outcome!=="RETURNED_TO_CARRIER"&&<section className="rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="text-lg font-black">Teslim edilemeyen gönderiyi siparişle eşleştir</h2><p className="mt-1 text-sm font-semibold">Kargo barkodu mevcut sistemde doğrudan sipariş takip numarasıyla tutulmadığı için sipariş numarasıyla doğrulama zorunludur.</p><form action={matchCargoPreReceiptToOrder} className="mt-3 flex gap-2"><input type="hidden" name="preReceiptId" value={pre.id}/><input name="orderNumber" required className="flex-1 rounded-xl border p-3 font-mono font-bold uppercase" placeholder="SIP..."/><button className="rounded-xl bg-amber-600 px-5 font-black text-white">Siparişle Eşleştir</button></form></section>}

   {pre.ecommerceReturn&&pre.originalOrder&&["RETURN_ENTRY_PENDING","UNDELIVERED_RETURN"].includes(pre.outcome)&&<EcommerceReturnReceivingPanel preReceiptId={pre.id} returnNumber={pre.ecommerceReturn.returnNumber} orderNumber={pre.originalOrder.orderNumber} customerName={pre.originalOrder.customer.companyName} items={pre.ecommerceReturn.items.map(i=>({id:i.id,productCode:i.productCode,productBarcode:i.productBarcode,productName:i.productName,expectedQuantity:i.expectedQuantity,receivedQuantity:i.receivedQuantity,acceptedQuantity:i.acceptedQuantity,rejectedQuantity:i.rejectedQuantity,refundStatus:i.refundStatus,refundAmount:i.refundAmount}))}/>}

   {pre.ecommerceReturn&&pre.ecommerceReturn.inspections.some(x=>x.refundStatus==="REVIEW_REQUIRED")&&<section className="mt-4 rounded-2xl border border-amber-300 bg-amber-50 p-5"><h2 className="text-lg font-black">Finans / Kalite İncelemesi</h2><p className="mt-1 text-sm font-semibold">Satılabilir dışı kalite sonucu alan birimler otomatik para iadesine geçmez. Yetkili kullanıcı birim bazında karar verir.</p><div className="mt-3 space-y-2">{pre.ecommerceReturn.inspections.filter(x=>x.refundStatus==="REVIEW_REQUIRED").map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-white p-3"><div><b>{x.ecommerceReturnItem.productCode} - {x.ecommerceReturnItem.productName}</b><br/><span className="text-xs">{x.qualityResult} · {x.targetHandlingUnitBarcode} · {x.targetLocationCode}</span></div><div className="flex gap-2"><form action={resolveEcommerceReturnInspectionRefund}><input type="hidden" name="inspectionId" value={x.id}/><input type="hidden" name="decision" value="APPROVE"/><button className="rounded-lg bg-emerald-600 px-3 py-2 font-black text-white">Para İadesini Onayla</button></form><form action={resolveEcommerceReturnInspectionRefund}><input type="hidden" name="inspectionId" value={x.id}/><input type="hidden" name="decision" value="REJECT"/><button className="rounded-lg bg-red-600 px-3 py-2 font-black text-white">Reddet</button></form></div></div>)}</div></section>}

   {pre.ecommerceReturn&&["WAREHOUSE_COMPLETED","FINANCE_PENDING","COMPLETED"].includes(pre.ecommerceReturn.status)&&<section className="mt-4 rounded-2xl border bg-white p-5"><h2 className="text-lg font-black">Finans Sonucu</h2><div className="mt-2 flex items-center justify-between"><div><p>Durum: <b>{statusLabel(pre.ecommerceReturn.refundStatus)}</b></p><p>İadeye uygun tutar: <b>{pre.ecommerceReturn.items.reduce((s,i)=>s+i.refundAmount,0).toFixed(2)} TL</b></p></div>{pre.ecommerceReturn.status==="WAREHOUSE_COMPLETED"&&pre.ecommerceReturn.refundStatus==="ELIGIBLE"&&<form action={createRefundApprovalRecord}><input type="hidden" name="ecommerceReturnId" value={pre.ecommerceReturn.id}/><button className="rounded-xl bg-emerald-600 px-5 py-3 font-black text-white">Finans İade Talebi Oluştur</button></form>}{pre.ecommerceReturn.status==="WAREHOUSE_COMPLETED"&&pre.ecommerceReturn.refundStatus==="REJECTED"&&<form action={closeEcommerceReturnWithoutRefund}><input type="hidden" name="ecommerceReturnId" value={pre.ecommerceReturn.id}/><button className="rounded-xl bg-slate-700 px-5 py-3 font-black text-white">Para İadesiz Kapat</button></form>}</div>
   {pre.ecommerceReturn.refunds.map(r=><div key={r.id} className="mt-3 rounded-xl border p-3"><div className="flex items-center justify-between"><p><b>{r.amount.toFixed(2)} TL</b> · {statusLabel(r.status)} · {r.provider??"-"}</p>{r.status==="REQUESTED"&&<form action={markEcommerceRefundCompleted} className="flex gap-2"><input type="hidden" name="refundId" value={r.id}/><input name="providerReference" required className="rounded-lg border px-3 py-2" placeholder="Banka/ödeme referansı"/><button className="rounded-lg bg-blue-700 px-3 py-2 font-black text-white">Para İadesi Yapıldı</button></form>}</div>{r.providerReference&&<p className="mt-1 text-xs">Referans: {r.providerReference}</p>}</div>)}
   <p className="mt-3 rounded-xl bg-blue-50 p-3 text-xs font-semibold text-blue-900">Gerçek ödeme sağlayıcısı entegrasyonu bağlanana kadar finans kaydı manuel referansla kapatılır; sistem banka/kart işlemi yaptığını varsaymaz.</p></section>}
  </div>}

  <section className="mt-6 rounded-2xl border bg-white p-5"><h2 className="mb-3 text-lg font-black">Son E-Ticaret İadeleri</h2>{recent.length?<div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr>{["İade No","Sipariş","Müşteri","Ön Kabul","Durum","Finans","Beklenen","Gelen"].map(x=><th key={x} className="border-b p-2 text-left">{x}</th>)}</tr></thead><tbody>{recent.map(r=><tr key={r.id}><td className="p-2 font-bold">{r.returnNumber}</td><td className="p-2">{r.originalOrder.orderNumber}</td><td className="p-2">{r.originalOrder.customer.companyName}</td><td className="p-2">{r.preReceipts[0]?.preReceiptNumber??"-"}</td><td className="p-2">{statusLabel(r.status)}</td><td className="p-2">{statusLabel(r.refundStatus)}</td><td className="p-2">{r.items.reduce((s,i)=>s+i.expectedQuantity,0)}</td><td className="p-2">{r.items.reduce((s,i)=>s+i.receivedQuantity,0)}</td></tr>)}</tbody></table></div>:<p className="text-slate-500">Henüz E-Ticaret iade kaydı yok.</p>}</section>
 </div>;
}
