export const PURCHASE_ORDER_IMPORT_TEMPLATE = {
  fileName:
    "etken-satinalma-siparisi-aktarim-sablonu.xlsx",

  orderSheetName:
    "SatinalmaSiparisleri",

  lineSheetName:
    "SiparisSatirlari",

  orderColumns: [
    {
      key:
        "purchaseNumber",
      header:
        "SiparisNo",
      required:
        true,
      width:
        20,
    },
    {
      key:
        "supplierName",
      header:
        "TedarikciAdi",
      required:
        true,
      width:
        32,
    },
    {
      key:
        "status",
      header:
        "Durum",
      required:
        false,
      width:
        20,
    },
    {
      key:
        "orderDate",
      header:
        "SiparisTarihi",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "expectedDate",
      header:
        "BeklenenTeslimTarihi",
      required:
        false,
      width:
        24,
    },
    {
      key:
        "paymentTermDays",
      header:
        "OdemeVadesiGun",
      required:
        false,
      width:
        18,
    },
    {
      key:
        "discountRate",
      header:
        "IskontoOrani",
      required:
        false,
      width:
        16,
    },
    {
      key:
        "supplierNote",
      header:
        "TedarikciNotu",
      required:
        false,
      width:
        36,
    },
    {
      key:
        "internalNote",
      header:
        "DahiliNot",
      required:
        false,
      width:
        36,
    },
  ],

  lineColumns: [
    {
      key:
        "purchaseNumber",
      header:
        "SiparisNo",
      required:
        true,
      width:
        20,
    },
    {
      key:
        "productCode",
      header:
        "UrunKodu",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "orderedQuantity",
      header:
        "SiparisMiktari",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "unitPrice",
      header:
        "BirimFiyat",
      required:
        true,
      width:
        16,
    },
    {
      key:
        "vatRate",
      header:
        "KDVOrani",
      required:
        true,
      width:
        14,
    },
  ],
} as const;