export const SALES_ORDER_IMPORT_TEMPLATE = {
  fileName:
    "etken-sevk-siparisi-aktarim-sablonu.xlsx",

  orderSheetName:
    "SevkSiparisleri",

  lineSheetName:
    "SiparisSatirlari",

  orderColumns: [
    {
      key:
        "orderNumber",
      header:
        "SiparisNo",
      required:
        true,
      width:
        20,
    },
    {
      key:
        "customerCode",
      header:
        "MusteriKodu",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "shippingAddressTitle",
      header:
        "AdresBasligi",
      required:
        false,
      width:
        24,
    },
    {
      key:
        "status",
      header:
        "Durum",
      required:
        false,
      width:
        18,
    },
    {
      key:
        "orderDate",
      header:
        "SiparisTarihi",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "requestedDate",
      header:
        "TalepEdilenTeslimTarihi",
      required:
        false,
      width:
        26,
    },
    {
      key:
        "paymentTermDays",
      header:
        "OdemeVadesiGun",
      required:
        false,
      width:
        18,
    },
    {
      key:
        "discountRate",
      header:
        "IskontoOrani",
      required:
        false,
      width:
        16,
    },
    {
      key:
        "customerNote",
      header:
        "MusteriNotu",
      required:
        false,
      width:
        36,
    },
    {
      key:
        "internalNote",
      header:
        "DahiliNot",
      required:
        false,
      width:
        36,
    },
  ],

  lineColumns: [
    {
      key:
        "orderNumber",
      header:
        "SiparisNo",
      required:
        true,
      width:
        20,
    },
    {
      key:
        "productCode",
      header:
        "UrunKodu",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "quantity",
      header:
        "SiparisMiktari",
      required:
        true,
      width:
        18,
    },
    {
      key:
        "unitPrice",
      header:
        "BirimFiyat",
      required:
        true,
      width:
        16,
    },
    {
      key:
        "vatRate",
      header:
        "KDVOrani",
      required:
        true,
      width:
        14,
    },
  ],
} as const;