import Link from "next/link";
import { prisma } from "@/lib/prisma";

const groups=[
 {title:"Genel Yönetim",sub:"Merkezi yönetim ve şirket ayarları",tone:"from-blue-600 to-blue-500",icon:"chart",links:[["Dashboard","/admin/dashboard"],["3PL Şirket Yapısı","/admin/wms-structure"],["B2B Ödeme Ayarları","/admin/b2b-settings"]]},
 {title:"Ürün Yönetimi",sub:"Ürün, kategori ve veri yönetimi",tone:"from-emerald-600 to-emerald-500",icon:"box",links:[["Ürün Yönetimi","/admin/products"],["Ürün Veri Zenginleştirme","/admin/products/enrichment"],["Rakip Ürün İnceleme","/admin/products/enrichment/review"],["Barkod İnceleme","/admin/products/enrichment/barcode-review"],["Ürün Görsel Yönetimi","/admin/product-images"],["Rakip Fiyat Analizi","/admin/competitor-prices"],["Kategori Yönetimi","/admin/categories"],["Marka Yönetimi","/admin/brands"]]},
 {title:"Ticari Yönetim",sub:"Tedarikçi, müşteri ve sipariş",tone:"from-orange-500 to-amber-500",icon:"users",links:[["Tedarikçi Yönetimi","/admin/suppliers"],["Müşteri Yönetimi","/admin/customers"],["Sipariş Yönetimi","/admin/orders"],["Satın Alma","/admin/purchase-orders"]]},
 {title:"Stok Yönetimi",sub:"Stok hareketleri ve sayım işlemleri",tone:"from-violet-600 to-purple-500",icon:"stock",links:[["Barkod Yazıcıları","/admin/barcode-printers"],["Stok Hareketleri","/admin/stock/movements"],["Manuel Stok İşlemi","/admin/stock/manual"],["Lokasyon Bazlı Stok","/admin/stock/locations"],["Lokasyon Stok Haritası","/admin/stock/location-map"],["Planlı Sayımlar","/admin/inventory-counts"],["Sayım Raporları","/admin/inventory-counts/reports"]]},
 {title:"Handling Unit",sub:"Koli, palet ve adresleme yönetimi",tone:"from-rose-600 to-red-500",icon:"link",links:[["Koli / Palet Yönetimi","/admin/handling-units"],["Koli / Palet Transferi","/admin/handling-units/transfers"],["Toplu Birleştirme","/admin/handling-units/merge"],["Koli-Palet Bağlama","/admin/handling-units/pallet-link"],["Tekli Adresleme","/admin/handling-units/addressing"],["Toplu Adresleme","/admin/handling-units/addressing/bulk"],["Adres Kaldırma","/admin/handling-units/unaddressing"]]},
 {title:"WMS Operasyonları",sub:"Wave ve depo operasyon yönetimi",tone:"from-cyan-600 to-sky-500",icon:"wave",links:[["WMS Dashboard","/admin/wms-dashboard"],["THM Sorgu","/admin/manual-wave/product-query"],["Dağıtım Performansı","/admin/manual-wave/distribution-summary"],["Wave Dağılım Özeti","/admin/manual-wave/wave-summary"],["Wave Yönetimi","/admin/waves"],["Yeni Wave Oluştur","/admin/waves/new"]]},
 {title:"Depo Yönetimi",sub:"Depo ve lokasyon yapısı",tone:"from-indigo-600 to-blue-500",icon:"warehouse",links:[["Depo Yönetimi","/admin/warehouses"]]},
 {title:"Sistem Yönetimi",sub:"Veri, kullanıcı ve yetkilendirme",tone:"from-amber-500 to-yellow-500",icon:"gear",links:[["Excel Veri Aktarımı","/admin/data-imports"],["Kullanıcı Yönetimi","/admin/users"],["Rol ve Yetki Yönetimi","/admin/roles"]]},
 {title:"RF Operasyon Merkezi",sub:"El terminali operasyon ekranı",tone:"from-fuchsia-700 to-violet-600",icon:"terminal",links:[["RF Operasyon Merkezi","/rf"]]},
] as const;

function Icon({name}:{name:string}){const common="h-6 w-6"; if(name==="users")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="9" cy="8" r="3"/><path d="M3 20v-2a5 5 0 0 1 10 0v2M16 5a3 3 0 0 1 0 6M16 14a5 5 0 0 1 5 5v1"/></svg>;if(name==="box")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m4 7 8-4 8 4-8 4-8-4Z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/></svg>;if(name==="terminal")return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M9 6h6M10 18h4"/></svg>;return <svg className={common} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 16v-5M12 16V7M17 16v-3"/></svg>}

export default async function AdminHome(){
 const [products,customers,orders,stock,recent]=await Promise.all([
  prisma.product.count({where:{isActive:true}}),prisma.customer.count({where:{isActive:true}}),
  prisma.order.count({where:{status:{in:["APPROVED","PREPARING","PICKING","PACKING","READY_TO_SHIP"]}}}),
  prisma.product.aggregate({_sum:{stock:true}}),
  prisma.wmsOperationLog.findMany({take:4,orderBy:{createdAt:"desc"},select:{id:true,operationType:true,description:true,operatorName:true,isSuccessful:true,createdAt:true}})
 ]);
 const fmt=(n:number)=>n.toLocaleString("tr-TR");
 return <section className="p-4 sm:p-5 lg:p-6">
  <section className="relative min-h-[190px] overflow-hidden rounded-2xl bg-gradient-to-r from-[#0b63ce] via-[#1176d7] to-[#1a8ae0] shadow-sm">
   <div className="absolute inset-0 opacity-20" style={{backgroundImage:"linear-gradient(90deg,transparent 49%,#fff 50%,transparent 51%),linear-gradient(transparent 49%,#fff 50%,transparent 51%)",backgroundSize:"52px 52px"}}/>
   <div className="relative z-10 max-w-2xl p-7 text-white"><p className="text-sm font-black tracking-[.22em]">ETKEN OFİS</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">Yönetim ve WMS Merkezi</h1><p className="mt-3 max-w-xl text-sm font-medium text-blue-50 sm:text-base">Depo, ürün, sipariş ve iş ortakları yönetimi için merkezi kontrol paneli.</p></div>
   <div className="absolute -bottom-12 right-16 hidden h-[260px] w-[138px] rotate-[-8deg] rounded-[30px] border-[8px] border-[#071426] bg-[#123b67] p-3 shadow-2xl md:block"><div className="h-full rounded-[18px] bg-gradient-to-b from-[#1475c9] to-[#063b70] p-3 text-center text-white"><div className="mt-7 text-5xl font-black italic">e</div><div className="mt-2 text-sm font-black">ETKEN OFİS</div><div className="mt-1 text-[7px] tracking-[.18em]">KURUMSAL TEDARİK</div><div className="mx-auto mt-8 h-8 w-8 rounded-full border-2 border-blue-200/60"/></div></div>
   <div className="absolute right-[215px] top-5 hidden text-white/20 md:block"><svg width="300" height="160" viewBox="0 0 300 160" fill="none" stroke="currentColor"><path d="M0 30h300M0 75h300M0 120h300M40 0v160M110 0v160M180 0v160M250 0v160" strokeWidth="2"/></svg></div>
  </section>
  <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
   ["box","Toplam Ürün",fmt(products),"bg-blue-100 text-blue-700"],["chart","Aktif Sipariş",fmt(orders),"bg-emerald-100 text-emerald-700"],["users","Aktif Müşteri",fmt(customers),"bg-orange-100 text-orange-700"],["stock","Depo Stok",fmt(stock._sum.stock??0),"bg-violet-100 text-violet-700"]
  ].map(([i,l,v,t])=><article key={l} className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><span className={`flex h-12 w-12 items-center justify-center rounded-xl ${t}`}><Icon name={i}/></span><div><p className="text-sm font-semibold text-slate-500">{l}</p><p className="text-2xl font-black text-[#071426]">{v}</p></div></article>)}</div>
  <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(g=><article key={g.title} className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div className={`flex items-center gap-3 bg-gradient-to-r ${g.tone} px-4 py-3 text-white`}><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-white/20"><Icon name={g.icon}/></span><div><h2 className="font-black">{g.title}</h2><p className="text-xs text-white/85">{g.sub}</p></div></div><div className="divide-y divide-slate-100 px-3">{g.links.map(([l,h])=><Link key={h} href={h} className="flex items-center gap-3 px-2 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 hover:text-blue-700"><span className="h-1.5 w-1.5 rounded-full bg-blue-500"/><span className="flex-1">{l}</span><span className="text-blue-500">›</span></Link>)}</div></article>)}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[2fr_1fr]"><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-black text-slate-900">Son İşlemler</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-left text-slate-500"><tr><th className="p-2">Tarih</th><th className="p-2">İşlem</th><th className="p-2">Açıklama</th><th className="p-2">Kullanıcı</th><th className="p-2">Durum</th></tr></thead><tbody>{recent.map(x=><tr key={x.id} className="border-t border-slate-100"><td className="p-2">{x.createdAt.toLocaleString("tr-TR")}</td><td className="p-2">{x.operationType}</td><td className="p-2">{x.description??"-"}</td><td className="p-2">{x.operatorName??"-"}</td><td className={`p-2 font-bold ${x.isSuccessful?"text-emerald-600":"text-red-600"}`}>{x.isSuccessful?"Başarılı":"Hata"}</td></tr>)}</tbody></table></div></section><section className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h3 className="font-black text-slate-900">Hızlı Erişim</h3><div className="mt-3 grid grid-cols-2 gap-2">{[["Yeni Wave","/admin/waves/new"],["THM Sorgu","/admin/manual-wave/product-query"],["Stok Hareketleri","/admin/stock/movements"],["Ürün Yönetimi","/admin/products"]].map(([l,h])=><Link key={h} href={h} className="rounded-lg border border-blue-100 bg-blue-50/50 p-3 text-center text-xs font-bold text-blue-800 hover:bg-blue-100">{l}</Link>)}</div></section></div>
 </section>
}