"use client";
import { useMemo, useState } from "react";
import ColumnVisibilityMenu, { useColumnVisibility } from "@/components/admin/ColumnVisibilityMenu";
const columns=[{key:"warehouseCode",label:"Depo Kodu"},{key:"productCode",label:"Ürün Kodu"},{key:"barcode",label:"Barkod"},{key:"productName",label:"Ürün Tanımı"},{key:"brand",label:"Marka"},{key:"category",label:"Kategori"},{key:"mainCategory",label:"Ana Kategori"},{key:"subCategory",label:"Alt Kategori"},{key:"supplierName",label:"Tedarikçi İsmi"},{key:"blockedStock",label:"Bloke Stok"},{key:"planableStock",label:"Planlanabilir Stok"},{key:"reservedStock",label:"Rezerve Stok"}];
export type GeneralStockReportRow={id:number;warehouseCode:string;productCode:string;barcode:string;productName:string;brand:string;category:string;mainCategory:string;subCategory:string;supplierName:string;blockedStock:number;planableStock:number;reservedStock:number};
const numeric=new Set(["blockedStock","planableStock","reservedStock"]);
export default function GeneralStockReportTable({rows}:{rows:GeneralStockReportRow[]}){
 const state=useColumnVisibility("etken:columns:general-stock-report",columns); const shown=state.orderedColumns.filter(c=>state.isVisible(c.key)); const [filters,setFilters]=useState<Record<string,string>>({});
 const filtered=useMemo(()=>rows.filter(r=>shown.every(c=>{const f=(filters[c.key]??"").trim().toLocaleLowerCase("tr-TR");return !f||String(r[c.key as keyof GeneralStockReportRow]??"").toLocaleLowerCase("tr-TR").includes(f)})),[rows,shown,filters]);
 return <><div className="mt-7 flex flex-wrap items-center justify-between gap-3"><div className="text-sm font-semibold text-slate-500">{filtered.length} kayıt</div><ColumnVisibilityMenu columns={columns} visible={state.visible} order={state.order} onToggle={state.toggle} onMove={state.move} onShowAll={state.showAll} onReset={state.reset}/></div>
 <div className="mt-3 overflow-x-auto rounded-2xl bg-white shadow"><table className="min-w-full text-sm"><thead className="bg-slate-100"><tr>{shown.map(c=><th key={c.key} draggable onDragStart={e=>{e.dataTransfer.effectAllowed="move";e.dataTransfer.setData("text/plain",c.key)}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();state.move(e.dataTransfer.getData("text/plain"),c.key)}} className={`cursor-move select-none whitespace-nowrap p-3 ${numeric.has(c.key)?"text-right":"text-left"}`}>{c.label}</th>)}</tr>
 <tr className="border-t border-slate-200 bg-white">{shown.map(c=><th key={c.key} className="p-2"><input value={filters[c.key]??""} onChange={e=>setFilters(x=>({...x,[c.key]:e.target.value}))} placeholder="Filtrele..." className={`w-full min-w-28 rounded-lg border border-slate-200 px-2 py-1.5 text-xs font-normal ${numeric.has(c.key)?"text-right":"text-left"}`}/></th>)}</tr></thead>
 <tbody>{filtered.map(r=><tr key={r.id} className="border-t hover:bg-slate-50">{shown.map(c=><td key={c.key} className={`whitespace-nowrap p-3 ${numeric.has(c.key)?"text-right tabular-nums font-bold":""} ${c.key==="productCode"?"font-bold":""}`}>{r[c.key as keyof GeneralStockReportRow]}</td>)}</tr>)}{filtered.length===0&&<tr><td colSpan={Math.max(1,shown.length)} className="p-12 text-center text-slate-500">Filtrelere uygun stok kaydı bulunamadı.</td></tr>}</tbody></table></div></>
}
