import Link from "next/link";
import ShippingAdminForm from "@/components/admin/shipping/ShippingAdminForm";
import { bulkPlanShipmentAction, createShipmentAction } from "./actions";
import { ShipmentPlanningService } from "@/modules/fulfillment/services/shipment-planning.service";
const tr=(s:string)=>({CREATED:"OLUŞTURULDU",ROUTING:"ROTALANIYOR",ROUTED:"ROTALANDI",LOADING:"YÜKLENİYOR",LOADED:"YÜKLENDİ",SHIPPED:"SEVK EDİLDİ"}[s]??s);
export default async function Page(){
 const[carriers,vehicles,routes,shipments,ready]=await Promise.all([ShipmentPlanningService.listCarriers(),ShipmentPlanningService.listVehicles(),ShipmentPlanningService.listRoutes(),ShipmentPlanningService.listShipments(),ShipmentPlanningService.readyWaitingReport()]);
 const plannable=shipments.filter(x=>["CREATED","ROUTING","ROUTED"].includes(x.status));
 return <main><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-2xl font-black">Sevkiyat Planlama</h1><Link href="/admin/shipping-planning/dashboard" className="rounded-xl border bg-white px-4 py-3 font-bold">Operasyon Dashboard →</Link></div><p className="mb-5 text-slate-600">Taşıyıcı, araç, rota ve sevkiyat tarihini belirleyin; ardından sevke hazır THM'leri toplu olarak sevkiyata bağlayın.</p>
 <ShippingAdminForm action={createShipmentAction} submitLabel="Sevkiyat Numarası Oluştur" fields={[{name:"shipmentDate",label:"Sevkiyat Tarihi",type:"date",required:true},{name:"carrierId",label:"Taşıyıcı",options:carriers.filter(x=>x.isActive).map(x=>({value:x.id,label:x.name}))},{name:"vehicleId",label:"Araç",options:vehicles.filter(x=>x.isActive).map(x=>({value:x.id,label:x.plate+" · "+x.vehicleType}))},{name:"routeIds",label:"Rotalar (çoklu seçim)",required:true,multiple:true,options:routes.filter(x=>x.isActive).map(x=>({value:x.id,label:x.routeNumber+" · "+x.name}))},{name:"driverName",label:"Sürücü"},{name:"driverPhone",label:"Sürücü Telefon"},{name:"driverIdentityNo",label:"Sürücü Kimlik No"},{name:"notes",label:"Not"}]}/>
 <form action={bulkPlanShipmentAction} className="mt-6 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">Toplu THM Planlama</h2><p className="mt-1 text-sm text-slate-600">Çeki listesi basılmış ve henüz sevkiyata bağlanmamış THM'leri seçin.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select name="shipmentId" required className="rounded-xl border p-3"><option value="">Sevkiyat seçiniz</option>{plannable.map(x=><option key={x.id} value={x.id}>{x.shipmentNumber} · {tr(x.status)}</option>)}</select><select name="routeId" required className="rounded-xl border p-3"><option value="">Rota seçiniz</option>{routes.filter(x=>x.isActive).map(x=><option key={x.id} value={x.id}>{x.routeNumber} · {x.name}</option>)}</select></div>
 <div className="mt-4 max-h-96 overflow-auto rounded-xl border"><table className="w-full text-sm"><thead className="sticky top-0 bg-slate-100"><tr><th className="p-3">Seç</th><th className="p-3 text-left">THM</th><th className="p-3 text-left">Müşteri</th><th className="p-3">Hazır Tarihi</th></tr></thead><tbody>{ready.map(x=><tr key={x.id} className="border-t"><td className="p-3 text-center"><input type="checkbox" name="shippingHandlingUnitIds" value={x.id} className="h-5 w-5"/></td><td className="p-3 font-black">{x.handlingUnit.barcode}</td><td className="p-3">{x.customerCode} · {x.customerName}</td><td className="p-3 text-center">{x.readyAt?.toLocaleString("tr-TR")??"-"}</td></tr>)}</tbody></table>{!ready.length&&<p className="p-5 text-center font-bold text-slate-500">Planlanmayı bekleyen sevke hazır THM bulunmuyor.</p>}</div><button disabled={!ready.length} className="mt-4 rounded-xl bg-blue-950 px-6 py-3 font-black text-white disabled:opacity-40">SEÇİLEN THM'LERİ PLANLA</button></form>
 <div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-left">Sevkiyat No</th><th className="p-3">Tarih</th><th className="p-3 text-left">Taşıyıcı</th><th className="p-3 text-left">Araç</th><th className="p-3">THM</th><th className="p-3">Durum</th></tr></thead><tbody>{shipments.map(x=><tr key={x.id} className="border-t"><td className="p-3 font-black">{x.shipmentNumber}</td><td className="p-3 text-center">{x.shipmentDate.toLocaleDateString("tr-TR")}</td><td className="p-3">{x.carrier?.name??"-"}</td><td className="p-3">{x.vehicle?.plate??"-"}</td><td className="p-3 text-center">{x._count.handlingUnits}</td><td className="p-3 text-center font-bold">{tr(x.status)}</td></tr>)}</tbody></table></div></main>
}