import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
function loc(l:{code:string;section:string;level:string;bin:string}){return [l.code,l.section,l.level,l.bin].filter(Boolean).join("-")}
export default async function RFProductQueryPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 await AuthorizationService.requireRfAccess("INVENTORY_VIEW"); const {q=""}=await searchParams; const scan=q.trim();
 const items=scan?await prisma.handlingUnitItem.findMany({where:{quantity:{gt:0},product:{OR:[{barcode:scan},{code:scan}]}},orderBy:[{handlingUnit:{warehouse:{code:"asc"}}},{handlingUnit:{location:{sortOrder:"asc"}}},{handlingUnit:{barcode:"asc"}}],select:{quantity:true,product:{select:{code:true,name:true,barcode:true}},handlingUnit:{select:{barcode:true,warehouse:{select:{code:true,name:true}},location:{select:{code:true,section:true,level:true,bin:true}}}}}}):[];
 const p=items[0]?.product;
 return <section><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">RF Sorgu</p><h1 className="mt-1 text-2xl font-black">Ürün Sorgula</h1></div><Link href="/rf" className="rounded-xl border bg-white px-4 py-3 font-bold">← Menü</Link></div>
 <form className="rounded-2xl border border-blue-200 bg-white p-4 shadow-sm"><label className="text-sm font-black">Ürün Okut</label><div className="mt-2 flex gap-2"><input autoFocus name="q" defaultValue={scan} placeholder="Ürün barkodu okutun" className="min-w-0 flex-1 rounded-xl border px-4 py-4 text-lg font-bold"/><button className="rounded-xl bg-blue-900 px-5 py-3 font-black text-white">Sorgula</button></div></form>
 {scan&&!p&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">Ürün bulunamadı.</div>}
 {p&&<><div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">DEPO</p><p className="mt-1 font-black">{Array.from(new Set(items.map(i=>i.handlingUnit.warehouse?.code).filter(Boolean))).join(", ")||"-"}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">ÜRÜN KODU</p><p className="mt-1 font-black">{p.code}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">ÜRÜN TANIMI</p><p className="mt-1 font-black">{p.name}</p></div></div>
 <div className="mt-4 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-left">SKU</th><th className="p-3 text-left">Ürün Tanımı</th><th className="p-3 text-left">Lokasyon</th><th className="p-3 text-left">THM</th><th className="p-3 text-right">Miktar</th></tr></thead><tbody>{items.map((i,n)=><tr key={n} className="border-t"><td className="p-3 font-bold">{i.product.code}</td><td className="p-3">{i.product.name}</td><td className="p-3">{i.handlingUnit.location?loc(i.handlingUnit.location):"-"}</td><td className="p-3 font-bold">{i.handlingUnit.barcode}</td><td className="p-3 text-right font-black">{i.quantity.toLocaleString("tr-TR")}</td></tr>)}</tbody></table></div></>}</section>
}