import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
import { saveBoxDefinitionAction } from "./actions";

export default async function Page({searchParams}:{searchParams:Promise<{edit?:string}>}){
 await AuthorizationService.requirePermission("SHIPPING_EXECUTE");
 const p=await searchParams;
 const [warehouses,rows]=await Promise.all([
  prisma.warehouse.findMany({where:{isActive:true},orderBy:{code:"asc"},select:{id:true,code:true,name:true}}),
  prisma.shippingBoxDefinition.findMany({where:{tenantId:"tenant_etken",companyId:"company_etken_office"},include:{warehouses:{include:{warehouse:{select:{code:true,name:true}}}}},orderBy:{code:"asc"}})
 ]);
 const edit=rows.find(x=>x.id===p.edit);
 return <main className="p-4 sm:p-6 lg:p-10"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-wider text-blue-700">Sevkiyat Planlama</p><h1 className="text-3xl font-black">Desi Bilgileri Tanımlama</h1><p className="mt-1 text-slate-600">Koli kodu, tipi, ölçüsü, desi ve kullanılacağı depoları tanımlayın.</p></div><Link href="/admin/shipping-planning" className="rounded-xl border bg-white px-4 py-3 font-bold">← Sevkiyat Planlama</Link></div>
 <form action={saveBoxDefinitionAction} className="mt-6 rounded-2xl border bg-white p-5 shadow-sm">{edit&&<input type="hidden" name="id" value={edit.id}/>}<div className="grid gap-4 md:grid-cols-4"><label className="font-bold">Koli Kodu<input name="code" required defaultValue={edit?.code??""} placeholder="B2B001" className="mt-1 w-full rounded-xl border p-3 uppercase"/></label><label className="font-bold">Koli Tipi<input name="boxType" required defaultValue={edit?.boxType??""} placeholder="B2B" className="mt-1 w-full rounded-xl border p-3 uppercase"/></label><label className="font-bold">Koli Ölçüsü<input name="dimensions" required defaultValue={edit?.dimensions??""} placeholder="15*20*20" className="mt-1 w-full rounded-xl border p-3"/></label><label className="font-bold">Desi<input name="desi" required type="number" min="0.01" step="0.01" defaultValue={edit?.desi??""} className="mt-1 w-full rounded-xl border p-3"/></label></div>
 <fieldset className="mt-5"><legend className="font-black">Depolar (çoklu seçim)</legend><div className="mt-2 grid gap-2 md:grid-cols-3">{warehouses.map(w=><label key={w.id} className="rounded-xl border p-3"><input type="checkbox" name="warehouseId" value={w.id} defaultChecked={edit?.warehouses.some(x=>x.warehouseId===w.id)??false} className="mr-2"/>{w.code} - {w.name}</label>)}</div></fieldset>
 <div className="mt-5 flex gap-3"><button className="rounded-xl bg-blue-950 px-6 py-3 font-black text-white">{edit?"Güncelle":"Ekle"}</button>{edit&&<Link href="/admin/shipping-planning/box-desi" className="rounded-xl border px-6 py-3 font-bold">Vazgeç</Link>}</div></form>
 <form action="/admin/shipping-planning/box-desi/print" method="get" target="_blank" className="mt-6 overflow-x-auto rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b p-4"><b>Koli Barkodu Yazdır</b><select name="layout" defaultValue="a4" className="rounded-xl border p-2"><option value="a4">A4 · 3×5 cm</option><option value="thermal">Termal · 3×5 cm</option></select><button className="rounded-xl bg-slate-900 px-5 py-2 font-bold text-white">Seçilenleri Yazdır</button></div><table className="min-w-full text-sm"><thead className="bg-slate-100"><tr>{["Seç","Koli Kodu","Koli Tipi","Koli Ölçüsü","Desi","Depolar","İşlem"].map(h=><th key={h} className="p-3 text-left">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-3"><input type="checkbox" name="id" value={r.id}/></td><td className="p-3 font-black">{r.code}</td><td className="p-3">{r.boxType}</td><td className="p-3">{r.dimensions}</td><td className="p-3">{r.desi}</td><td className="p-3">{r.warehouses.map(x=>x.warehouse.code).join(", ")}</td><td className="p-3"><Link href={"/admin/shipping-planning/box-desi?edit="+r.id} className="font-bold text-blue-800">Düzenle</Link></td></tr>)}</tbody></table></form></main>;
}