"use client";
import { FormEvent, useState } from "react";
import { commitSortingAction, resolveProductAction } from "@/app/rf/manual-wave/[waveId]/actions";

type Pending = Awaited<ReturnType<typeof resolveProductAction>>;
export default function ManualWaveSortingClient({ waveId }: { waveId: string }) {
  const [picking, setPicking] = useState(""); const [product, setProduct] = useState(""); const [thm, setThm] = useState("");
  const [pending, setPending] = useState<Pending | null>(null); const [message, setMessage] = useState(""); const [progress, setProgress] = useState({ planned: 0, distributed: 0, remaining: 0, complete: false });
  function error(value: unknown) { setMessage(value instanceof Error ? value.message : "İşlem başarısız."); const audio = new AudioContext(); const oscillator = audio.createOscillator(); oscillator.frequency.value = 220; oscillator.connect(audio.destination); oscillator.start(); oscillator.stop(audio.currentTime + .15); }
  async function resolve(e: FormEvent) { e.preventDefault(); try { const next = await resolveProductAction(waveId, picking, product); setPending(next); setMessage("Ürün beklemede; THM okutulmadan miktar değişmez."); speechSynthesis.speak(new SpeechSynthesisUtterance(`${next.priorityRank}. mağaza`)); } catch (e) { error(e); } }
  async function commit(e: FormEvent) { e.preventDefault(); if (!pending) return; try { const next = await commitSortingAction({ waveId, pickingBarcode: picking, productBarcode: product, expectedDistributionId: pending.distributionId, thmBarcode: thm, idempotencyKey: crypto.randomUUID() }); setProgress(next); setPending(null); setProduct(""); setThm(""); setMessage(next.complete ? "Wave ayrıştırması tamamlandı." : "Dağıtım kaydedildi."); } catch (e) { error(e); } }
  return <main className="mx-auto max-w-xl space-y-4 p-4"><h1 className="text-2xl font-bold">Manuel Wave Ayrıştırma</h1><label className="block">Toplama barkodu<input className="w-full border p-3" value={picking} onChange={e => setPicking(e.target.value)} autoFocus /></label><form onSubmit={resolve}><label className="block">Ürün barkodu<input className="w-full border p-3" value={product} onChange={e => setProduct(e.target.value)} /></label><button className="mt-2 bg-blue-700 p-3 text-white">Hedefi bul</button></form>{pending && <section className="rounded border p-4"><strong>{pending.priorityRank}. mağaza</strong><p>Hedef: {pending.targetCode}</p><p>Kalan: {pending.remainingQuantity}</p><form onSubmit={commit}><input aria-label="THM barkodu" placeholder="ST-..." className="w-full border p-3" value={thm} onChange={e => setThm(e.target.value)} /><button className="mt-2 bg-green-700 p-3 text-white">THM ile onayla</button></form></section>}<p role="status">{message}</p><p>İlerleme: {progress.distributed}/{progress.planned} — Kalan {progress.remaining}</p></main>;
}
