import {AuthorizationService} from "@/modules/authorization/services/authorization.service";
import {prisma} from "@/lib/prisma";
import {savePaymentGatewayAction} from "./actions";
export default async function Page(){
 await AuthorizationService.requirePermission("ORDER_MANAGE");
 const rows=await prisma.paymentGatewaySetting.findMany({where:{tenantId:"tenant_etken",companyId:"company_etken_office"},orderBy:{provider:"asc"}});
 return <main className="p-4 sm:p-6 lg:p-10"><p className="text-xs font-black uppercase text-[#EF4B23]">E-Ticaret Yönetimi</p><h1 className="mt-2 text-3xl font-black">Sanal POS / Kredi Kartı Entegrasyonu</h1>
 <p className="mt-2 max-w-4xl text-sm text-slate-600">Kart numarası, CVV veya son kullanma tarihi ETKEN veritabanında tutulmaz. Sağlayıcı adaptörü bağlandığında 3D Secure başlatma, callback doğrulama, ödeme, hata ve iade kayıtları PaymentTransaction üzerinden yönetilir. API anahtarlarını bu ekrana yazmayın; canlı kimlik bilgileri Secret Manager üzerinden bağlanmalıdır.</p>
 <form action={savePaymentGatewayAction} className="mt-6 grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2"><input name="provider" required placeholder="Sağlayıcı kodu (örn. IYZICO)" className="rounded-xl border p-3 uppercase"/><input name="displayName" required placeholder="Görünen ad" className="rounded-xl border p-3"/>
 <label className="text-sm font-bold">Durum<select name="isActive" defaultValue="false" className="mt-1 w-full rounded-xl border p-3"><option value="false">Pasif</option><option value="true">Aktif</option></select></label><label className="text-sm font-bold">Ortam<select name="testMode" defaultValue="true" className="mt-1 w-full rounded-xl border p-3"><option value="true">Test / Sandbox</option><option value="false">Canlı</option></select></label>
 <label className="text-sm font-bold">3D Secure<select name="threeDSecureRequired" defaultValue="true" className="mt-1 w-full rounded-xl border p-3"><option value="true">Zorunlu</option><option value="false">Opsiyonel</option></select></label><label className="text-sm font-bold">Taksit<select name="installmentEnabled" defaultValue="false" className="mt-1 w-full rounded-xl border p-3"><option value="false">Kapalı</option><option value="true">Açık</option></select></label><button className="rounded-xl bg-slate-900 px-5 py-3 font-black text-white md:col-span-2">Sağlayıcı Ayarını Kaydet</button></form>
 <div className="mt-6 overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-900 text-white"><tr><th className="p-3 text-left">Sağlayıcı</th><th>Durum</th><th>Ortam</th><th>3D</th><th>Taksit</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-3"><strong>{x.displayName}</strong><div className="text-xs text-slate-500">{x.provider}</div></td><td className="text-center">{x.isActive?"Aktif":"Pasif"}</td><td className="text-center">{x.testMode?"Test":"Canlı"}</td><td className="text-center">{x.threeDSecureRequired?"Zorunlu":"Opsiyonel"}</td><td className="text-center">{x.installmentEnabled?"Açık":"Kapalı"}</td></tr>)}</tbody></table></div></main>
}