import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
type Props={searchParams:Promise<{stockDate?:string;warehouseId?:string|string[];productCode?:string}>};
const arr=(v:string|string[]|undefined)=>Array.isArray(v)?v:v?[v]:[];
export default async function HistoricalStockPage({searchParams}:Props){
 await AuthorizationService.requirePermission("INVENTORY_VIEW"); const q=await searchParams;
 const ids=arr(q.warehouseId).map(Number).filter(Number.isInteger); const code=(q.productCode??"").trim().toUpperCase(); const stockDate=q.stockDate??"";
 const warehouses=await prisma.warehouse.findMany({where:{isActive:true},orderBy:{code:"asc"},select:{id:true,code:true,name:true}});
 let rows:Array<{warehouseId:number;warehouseCode:string;warehouseName:string;productId:number;productCode:string;productName:string;quantity:number}>=[];
 if(stockDate){const end=new Date(stockDate+"T23:59:59.999"); const movements=await prisma.stockMovement.findMany({where:{createdAt:{lte:end},warehouseId:{not:null,...(ids.length?{in:ids}:{})},...(code?{product:{code}}:{})},select:{warehouseId:true,physicalChange:true,warehouse:{select:{code:true,name:true}},product:{select:{id:true,code:true,name:true}}}});
 const map=new Map<string,(typeof rows)[number]>(); for(const m of movements){if(!m.warehouseId||!m.warehouse)continue;const k=m.warehouseId+":"+m.product.id;const x=map.get(k)??{warehouseId:m.warehouseId,warehouseCode:m.warehouse.code,warehouseName:m.warehouse.name,productId:m.product.id,productCode:m.product.code,productName:m.product.name,quantity:0};x.quantity+=m.physicalChange;map.set(k,x)} rows=[...map.values()].sort((a,b)=>a.warehouseCode.localeCompare(b.warehouseCode)||a.productCode.localeCompare(b.productCode));}
 return <main className="p-6 lg:p-10"><h1 className="text-4xl font-bold">Eski Tarihli Stok Raporu</h1><p className="mt-2 text-slate-500">Stok hareketlerinden seçilen gün sonundaki fiziksel stok bakiyesini hesaplar.</p>
 <form className="mt-7 rounded-2xl bg-white p-6 shadow"><div className="grid gap-5 lg:grid-cols-3"><label><b>Stok Tarihi</b><input type="date" name="stockDate" required defaultValue={stockDate} className="mt-2 w-full rounded-xl border p-3"/></label><fieldset><legend className="font-bold">Depo (çoklu)</legend><div className="mt-2 max-h-44 overflow-auto rounded-xl border p-3">{warehouses.map(w=><label key={w.id} className="flex gap-2 py-1"><input type="checkbox" name="warehouseId" value={w.id} defaultChecked={ids.includes(w.id)}/>{w.code} - {w.name}</label>)}</div></fieldset><label><b>Ürün Kodu</b><input name="productCode" defaultValue={code} placeholder="Boş = tüm ürünler" className="mt-2 w-full rounded-xl border p-3 uppercase"/></label></div><button className="mt-5 rounded-xl bg-blue-900 px-6 py-3 font-bold text-white">Raporu Getir</button></form>
 <div className="mt-7 overflow-x-auto rounded-2xl bg-white shadow"><table className="min-w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-left">Stok Tarihi</th><th className="p-3 text-left">Depo</th><th className="p-3 text-left">Ürün Kodu</th><th className="p-3 text-left">Ürün Tanımı</th><th className="p-3 text-right">Miktar</th></tr></thead><tbody>{rows.map(r=><tr key={r.warehouseId+":"+r.productId} className="border-t"><td className="p-3">{stockDate}</td><td className="p-3">{r.warehouseCode} - {r.warehouseName}</td><td className="p-3 font-bold">{r.productCode}</td><td className="p-3">{r.productName}</td><td className="p-3 text-right font-bold">{r.quantity}</td></tr>)}</tbody></table></div></main>
}