import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
function loc(l:{code:string;section:string;level:string;bin:string}){return [l.code,l.section,l.level,l.bin].filter(Boolean).join("-")}
export default async function RFAddressQueryPage({searchParams}:{searchParams:Promise<{q?:string}>}){
 await AuthorizationService.requireRfAccess("INVENTORY_VIEW"); const {q=""}=await searchParams; const scan=q.trim();
 const locations=scan?await prisma.warehouseLocation.findMany({where:{isActive:true},select:{id:true,code:true,section:true,level:true,bin:true,warehouse:{select:{code:true,name:true}},handlingUnits:{select:{barcode:true,items:{where:{quantity:{gt:0}},select:{quantity:true}}}}}}):[];
 const location=locations.find(l=>loc(l)===scan)||null;
 const rows=location?.handlingUnits.map(u=>({barcode:u.barcode,qty:u.items.reduce((t,i)=>t+i.quantity,0)})).filter(r=>r.qty>0)??[];
 return <section><div className="mb-4 flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-blue-700">RF Sorgu</p><h1 className="mt-1 text-2xl font-black">Adres Sorgula</h1></div><Link href="/rf" className="rounded-xl border bg-white px-4 py-3 font-bold">← Menü</Link></div>
 <form className="rounded-2xl border border-blue-200 bg-white p-4 shadow-sm"><label className="text-sm font-black">Adres Okut</label><div className="mt-2 flex gap-2"><input autoFocus name="q" defaultValue={scan} placeholder="Lokasyon barkodu okutun" className="min-w-0 flex-1 rounded-xl border px-4 py-4 text-lg font-bold"/><button className="rounded-xl bg-blue-900 px-5 py-3 font-black text-white">Sorgula</button></div></form>
 {scan&&!location&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">Lokasyon bulunamadı.</div>}
 {location&&<><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">DEPO</p><p className="mt-1 font-black">{location.warehouse.code+" · "+location.warehouse.name}</p></div><div className="rounded-xl border bg-white p-4"><p className="text-xs font-bold text-slate-500">LOKASYON</p><p className="mt-1 font-black">{loc(location)}</p></div></div>
 <div className="mt-4 overflow-hidden rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100"><tr><th className="p-3 text-left">THM</th><th className="p-3 text-right">THM İçi Miktar</th></tr></thead><tbody>{rows.map(r=><tr key={r.barcode} className="border-t"><td className="p-3 font-black">{r.barcode}</td><td className="p-3 text-right font-black">{r.qty.toLocaleString("tr-TR")}</td></tr>)}{rows.length===0&&<tr><td colSpan={2} className="p-4 text-center text-slate-500">Bu lokasyonda stoklu THM bulunmuyor.</td></tr>}</tbody></table></div></>}</section>
}