import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { AuthorizationService } from "@/modules/authorization/services/authorization.service";
import { ManualWaveReportingService,formatIstanbul } from "@/modules/manual-wave/services/manual-wave-reporting.service";
import { WmsContextService } from "@/modules/wms-context/services/wms-context.service";

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}) { const q=await searchParams; const user=await AuthorizationService.requirePermission("MANUAL_WAVE_REPORT_VIEW"); const scope=await WmsContextService.requireActiveContext(user.id,user.isAdminUser); const waves=await prisma.wave.findMany({where:{sortingLines:{some:{tenantId:scope.tenantId,companyId:scope.companyId,warehouseId:scope.warehouseId}}},select:{id:true,waveNo:true},orderBy:{createdAt:"desc"},take:200}); const waveId=q.waveId||waves[0]?.id; const filters={waveId:waveId||"",distributionId:q.distributionId||undefined,productId:q.productId?Number(q.productId):undefined}; const [summary,detail]=waveId?await Promise.all([ManualWaveReportingService.getWaveDistributionSummary(scope,filters),ManualWaveReportingService.getWaveDistributionDetail(scope,filters)]):[[],[]];
return <main className="p-6 space-y-5"><Link href="/admin">← Yönetime dön</Link><h1 className="text-2xl font-bold">Dalga Dağıtım Özeti</h1><form className="flex flex-wrap gap-3 rounded-xl border p-4"><select name="waveId" value={waveId}>{waves.map(w=><option key={w.id} value={w.id}>{w.waveNo}</option>)}</select><input name="distributionId" defaultValue={q.distributionId} placeholder="Hedef kimliği (opsiyonel)"/><input name="productId" type="number" defaultValue={q.productId} placeholder="Ürün kimliği (opsiyonel)"/><button className="rounded bg-slate-900 px-4 text-white">Uygula</button>{waveId&&<a href={`/admin/manual-wave/distribution-summary/export?${new URLSearchParams(Object.entries(q).filter((x):x is [string,string]=>Boolean(x[1])).concat(q.waveId?[]:[["waveId",waveId]]))}`} className="rounded bg-emerald-700 px-4 py-2 text-white">Excel (Özet + Detay)</a>}</form>
<section className="overflow-x-auto"><h2 className="font-bold">Mağaza özeti</h2><table className="w-full text-sm"><thead><tr>{["Öncelik","Mağaza","Müşteri","Planlanan","Aktif dağıtılan","Kalan","Tamamlanma","Aktif THM","Son işlem"].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{summary.map(r=><tr key={String(r.distributionId)} className="border-t"><td className="p-2">{String(r.priorityRank)}</td><td>{String(r.storeCode)}</td><td>{String(r.customerName)}</td><td>{String(r.planned)}</td><td>{String(r.distributed)}</td><td>{String(r.remaining)}</td><td>%{String(r.completion)}</td><td>{String(r.activeThmCount)}</td><td>{formatIstanbul(r.lastOperation as Date|null)}</td></tr>)}</tbody></table>{!summary.length&&<p className="p-4 text-slate-500">Dağıtım kaydı bulunamadı.</p>}</section>
<section className="overflow-x-auto"><h2 className="font-bold">Ürün detayı</h2><table className="w-full text-sm"><thead><tr>{["Ürün","Açıklama","Planlanan","Dağıtılan","Kalan","THM","Güncel THM barkodları"].map(x=><th key={x} className="p-2 text-left">{x}</th>)}</tr></thead><tbody>{detail.map((r,i)=><tr key={i} className="border-t"><td className="p-2">{String(r.productCode)}</td><td>{String(r.productName)}</td><td>{String(r.planned)}</td><td>{String(r.distributed)}</td><td>{String(r.remaining)}</td><td>{String(r.thmCount)}</td><td>{String(r.thmBarcodes||"-")}</td></tr>)}</tbody></table></section></main> }
