"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
type Lookup={orderNumber:string;shippingHandlingUnitBarcode:string;dispatchNumber:string|null;dispatchStatus:string|null;hasGiftNote:boolean;packingListPrintCount:number};
export default function EcommerceDocumentPrintScreen(){
 const ref=useRef<HTMLInputElement>(null); const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const [scan,setScan]=useState(""); const [data,setData]=useState<Lookup|null>(null); const [message,setMessage]=useState("Sipariş numarasını okutun."); const [busy,setBusy]=useState(false);
 useEffect(()=>{ref.current?.focus()},[]);
 async function lookup(raw:string){const value=raw.trim().toUpperCase();if(!value||busy)return;setBusy(true);setMessage(value+" aranıyor...");
  try{const r=await fetch("/api/admin/ecommerce/documents/lookup",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({orderNumber:value})});const j=await r.json();if(!r.ok||!j.success){setData(null);setMessage("HATA: "+(j.message??"Sipariş bulunamadı."));return;}setData(j);setMessage(j.orderNumber+" bulundu. Yeniden basılacak evrakı seçin.");}
  catch{setMessage("HATA: Evrak servisine ulaşılamadı.");}finally{setBusy(false);setScan("");requestAnimationFrame(()=>ref.current?.focus());}}
 function submit(e:FormEvent){e.preventDefault();void lookup(scan)}
 function openA4(kind:"dispatch"|"gift"){if(!data)return;window.open(`/api/admin/ecommerce/packaging/a4-print?thm=${encodeURIComponent(data.shippingHandlingUnitBarcode)}&kind=${kind}`,kind==="gift"?"ecommerce-gift-reprint":"ecommerce-dispatch-reprint","width=1000,height=800");}
 return <div className="p-6"><p className="text-sm font-semibold text-slate-500">E-Ticaret Yönetimi / E-Ticaret Evrak Basım</p><h1 className="mt-1 text-3xl font-black">E-Ticaret Evrak Basım</h1><p className="mt-1 text-sm text-slate-500">Sipariş numarasını okutarak Desi Çeki, İrsaliye ve Hediye Notunu yeniden basın.</p>
 <section className="mt-6 max-w-3xl rounded-2xl border bg-white p-6 shadow-sm"><form onSubmit={submit}><label className="mb-2 block font-bold">Sipariş Numarası Okut</label><input ref={ref} value={scan} onChange={e=>{const v=e.target.value.toUpperCase();setScan(v);if(timer.current)clearTimeout(timer.current);if(v.trim())timer.current=setTimeout(()=>void lookup(v),180)}} autoComplete="off" className="w-full rounded-xl border-2 border-blue-500 px-4 py-4 text-lg font-black uppercase outline-none" placeholder="SIP..."/></form><p className="mt-3 font-semibold text-blue-700">{message}</p></section>
 {data&&<section className="mt-4 max-w-3xl rounded-2xl border bg-white p-6 shadow-sm"><div className="grid grid-cols-2 gap-3 text-sm"><p><b>Sipariş:</b> {data.orderNumber}</p><p><b>Sevk THM:</b> {data.shippingHandlingUnitBarcode}</p><p><b>İrsaliye:</b> {data.dispatchNumber??"—"}</p><p><b>Çeki basım sayısı:</b> {data.packingListPrintCount}</p></div><div className="mt-6 grid grid-cols-3 gap-3"><button onClick={async()=>{await fetch("/api/admin/ecommerce/packaging/print-status",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({shippingHandlingUnitBarcode:data.shippingHandlingUnitBarcode})});setMessage("Desi Çeki yeniden yazdırılmış olarak işaretlendi (yazıcı tanımlı değil).")}} className="rounded-xl bg-blue-700 px-4 py-4 font-black text-white">Desi Çeki Yeniden Bas</button><button onClick={()=>openA4("dispatch")} className="rounded-xl bg-slate-800 px-4 py-4 font-black text-white">İrsaliye Yeniden Bas</button><button disabled={!data.hasGiftNote} onClick={()=>openA4("gift")} className="rounded-xl bg-amber-500 px-4 py-4 font-black text-white disabled:bg-slate-300">Hediye Notu Yeniden Bas</button></div></section>}
 </div>;
}
